version: '3'

services:
  postgres:
    image: postgres
    container_name: coffee-shop-db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"  # PostgreSQL portu
    networks:
      - pg-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: coffee-shop-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"  # pgAdmin portu
    networks:
      - pg-network

networks:
  pg-network:
    driver: bridge
